const crypto = require('node:crypto');

const SECRET_HEADERS = /^(authorization|cookie|set-cookie|x-api-key|api-key|token|password|secret)$/i;
function redactHeaders(headers = {}) { return Object.fromEntries(Object.entries(headers).map(([name, value]) => [name, SECRET_HEADERS.test(name) ? '[REDACTED]' : value])); }
function redactText(value = '') { return String(value).replace(/(authorization|cookie|set-cookie|api[-_]?key|token|password|secret)\s*[:=]\s*[^\s;,]+/gi, '$1: [REDACTED]').slice(0, 4000); }
function evidenceHash(value) { return crypto.createHash('sha256').update(String(value)).digest('hex').slice(0, 16); }
function normalizeAsset(value) { try { const url = new URL(value); url.hash = ''; url.pathname = url.pathname.replace(/\/+/g, '/').replace(/\/$/, '') || '/'; return url.toString(); } catch { return String(value).trim(); } }
function fingerprintOf({ type = 'configuration', asset = '', method = 'GET', parameter = '', evidence = '' }) { return `${type}|${method.toUpperCase()}|${normalizeAsset(asset)}|${parameter}|${evidenceHash(evidence)}`; }
function createFinding(input) { const evidenceText = input.evidence || input.detail || ''; const asset = input.asset || input.url || ''; const type = input.type || input.category || 'configuration'; const description = input.description || input.detail || ''; return { id: input.id || `finding-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`, type, category: type, title: input.title, severity: input.severity || 'Informational', confidence: input.confidence || 'Potential', source: input.source || 'passive-scanner', url: asset, asset, method: input.method || 'GET', parameter: input.parameter || '', description, detail: description, summary: description, impact: input.impact || 'Program ve bağlama göre manuel impact doğrulaması gerekir.', evidence: [{ source: input.source || 'passive-scanner', matched: redactText(evidenceText), timestamp: new Date().toISOString() }], request: input.request ? { ...input.request, headers: redactHeaders(input.request.headers) } : { method: input.method || 'GET', url: asset }, response: input.response ? { ...input.response, headers: redactHeaders(input.response.headers), bodySnippet: redactText(input.response.bodySnippet || '') } : undefined, reproduction: input.reproduction || ['Bulguyu program kurallarına uygun şekilde manuel doğrula.'], remediation: input.remediation || 'Programın güvenlik rehberine uygun server-side kontrol ekleyin.', references: input.references || [], cvss: input.cvss || null, status: input.status || 'New', reason: input.reason || 'Tek bir pasif sinyal gözlendi; kesinlik için manuel bağlamsal doğrulama gerekir.', fingerprint: input.fingerprint || fingerprintOf({ type, asset, method: input.method, parameter: input.parameter, evidence: evidenceText }), createdAt: input.createdAt || new Date().toISOString() }; }
module.exports = { createFinding, redactHeaders, redactText, fingerprintOf };
